# Import statements at the top in a separate cell

In [1]:
from modules.data_preparator import DataPreparator
from modules.scale_analyzer import ScaleAnalyzer
from modules.ensemble_creator import EnsembleModeler

# Set-up the data parameters

In [2]:
# Note: features are the independent variables
features = ['A1a', 'A1b', 'A2a', 'A2b', 'A2c', 'A2d', 'A2e', 'A2f', 'A2g', 'A2h', 'A3a', 'A3b', 'A3c', 'A3d',
                'A3e', 'A3f', 'A3g', 'A3h', 'A3i', 'A3j', 'A3k', 'A3l', 'A3m', 'A4', 'A4ai', 'A4aii', 'A4aiii',
                'A4aiv', 'A4av', 'A4avi', 'A4avii', 'B1a', 'B1b', 'B2a', 'B2b', 'B2c', 'B2d', 'B3a', 'B3b', 'B3c',
                'B3d', 'B4a', 'B4b', 'B4c', 'B4d', 'B5a', 'B5b', 'B5c', 'B5d', 'B6', 'B7a', 'B7b', 'B7c', 'B7d',
                'B7e', 'B8', 'B8ai', 'B8aii', 'B8aiii', 'B8aiv', 'B8av', 'B8avi', 'B8avii', 'B9', 'C1a', 'C1b', 'C1c',
                'C1d', 'C1e', 'C1f', 'C1g', 'C2', 'C3', 'C4a', 'C4b', 'C4c', 'C4d', 'C4e', 'C4f', 'C4g', 'C4h', 'C4i',
                'C4j', 'C4k', 'C4l', 'c4m', 'C4n', 'C4o', 'C4ii', 'C5', 'C6', 'C6ai', 'C6aii', 'C6aiii', 'C6aiv',
                'C6av', 'C6avi', 'C6avii', 'C6aviii', 'C6aix', 'C6ax', 'C6axi', 'C7', 'C8', 'C9', 'D3', 'D8', 'D14']
dep_var = 'AgencySize'

# Set-up the DataPreparator class

First we instantiate the class. In this example, I will use the option to pass the Path to the data file.

In [3]:
data_prep = DataPreparator(data="data/satisfaction/survey (1).csv", features=features, dep_var=dep_var, min_miss=100)

The following variables contain fewer than the min_miss cutoff of [100] and were dropped from the dataset: {'B7d', 'B8avi', 'C6avi', 'B7e', 'B8aiv', 'A4aiv', 'B8aii', 'B8ai', 'C6ai', 'A4av', 'A4', 'C6aii', 'A4avii', 'A4ai', 'B8avii', 'A4aiii', 'C6aiii', 'C6aviii', 'C6aix', 'C4ii', 'B8aiii', 'C6aiv', 'A4avi', 'C6avii', 'C6axi', 'A4aii', 'B7a', 'B8av', 'C6ax', 'C6av', 'B7b', 'B7c', 'C9'}

Now, we make the method call to split the data, specifying the parameters for the split

In [4]:
data_prep.split_data(val_set=False, test_size=.30, random_state=456)

We can access the training and testing data through the DataPreparator class if we need to. For the other classes we will use, we can just pass the instantiated data_handler and the rest is automatic!

In [5]:
data_prep.data

,A1a,A1b,A2a,A2b,A2c,A2d,A2e,A2f,A2g,A2h,...,C4n,C4o,C5,C6,C7,C8,D3,D8,D14,AgencySize
0,2.0,5.0,1.0,1.0,1.0,2.0,1.0,1.0,3.0,1.0,...,1.0,1.0,1.0,2.0,1.0,2.0,2,4.0,2.0,3
1,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,2.0,1.0,1.0,2,3.0,2.0,3
2,6.0,6.0,3.0,3.0,3.0,4.0,2.0,4.0,4.0,4.0,...,1.0,1.0,1.0,2.0,1.0,1.0,1,3.0,2.0,3
3,7.0,7.0,5.0,7.0,5.0,7.0,1.0,5.0,7.0,6.0,...,1.0,2.0,1.0,2.0,1.0,2.0,1,2.0,2.0,3
4,1.0,3.0,2.0,1.0,2.0,5.0,2.0,3.0,2.0,1.0,...,1.0,1.0,1.0,2.0,1.0,2.0,2,3.0,2.0,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2896,2.0,2.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,...,1.0,1.0,1.0,2.0,1.0,3.0,2,2.0,2.0,2
2897,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,...,1.0,1.0,1.0,2.0,1.0,1.0,2,4.0,1.0,2
2898,3.0,3.0,1.0,1.0,1.0,1.0,1.0,2.0,1.0,3.0,...,1.0,1.0,1.0,1.0,1.0,1.0,2,4.0,2.0,2
2899,2.0,2.0,2.0,2.0,2.0,3.0,2.0,2.0,2.0,2.0,...,1.0,1.0,1.0,2.0,1.0,2.0,2,3.0,2.0,2
2900,2.0,6.0,2.0,6.0,1.0,2.0,2.0,6.0,7.0,1.0,...,1.0,2.0,1.0,2.0,1.0,1.0,1,2.0,2.0,2

In [6]:
data_prep.x_train

,C1e,C4d,A2h,B2d,C1c,B4b,B4c,A3b,A3j,C4a,...,B9,A3d,B2b,A2e,c4m,B4d,D8,C4i,C1f,B4a
1422,2.0,1.0,1.0,2.0,1.0,3.0,2.0,3.0,3.0,2.0,...,3.0,1.0,2.0,1.0,1.0,2.0,4.0,1.0,2.0,5.0
2202,1.0,1.0,1.0,2.0,3.0,3.0,3.0,3.0,3.0,1.0,...,5.0,5.0,4.0,3.0,1.0,3.0,2.0,1.0,1.0,7.0
2249,1.0,1.0,2.0,4.0,1.0,1.0,2.0,3.0,3.0,1.0,...,3.0,3.0,2.0,1.0,1.0,3.0,1.0,1.0,1.0,2.0
738,7.0,1.0,1.0,7.0,7.0,2.0,1.0,2.0,1.0,5.0,...,5.0,2.0,1.0,1.0,5.0,3.0,3.0,1.0,2.0,2.0
2629,4.0,1.0,2.0,4.0,4.0,4.0,2.0,3.0,4.0,1.0,...,4.0,5.0,2.0,3.0,2.0,4.0,3.0,1.0,4.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1598,1.0,1.0,1.0,1.0,8.0,2.0,2.0,5.0,3.0,4.0,...,4.0,1.0,1.0,4.0,1.0,6.0,3.0,1.0,2.0,7.0
75,4.0,1.0,7.0,3.0,7.0,2.0,5.0,7.0,8.0,5.0,...,1.0,8.0,2.0,2.0,2.0,5.0,4.0,2.0,3.0,3.0
925,2.0,1.0,1.0,3.0,2.0,2.0,2.0,3.0,3.0,1.0,...,2.0,2.0,1.0,1.0,1.0,3.0,4.0,1.0,1.0,2.0
87,1.0,1.0,2.0,8.0,2.0,4.0,3.0,6.0,4.0,1.0,...,3.0,5.0,2.0,5.0,1.0,4.0,3.0,1.0,1.0,5.0
2457,4.0,1.0,2.0,4.0,4.0,4.0,4.0,3.0,4.0,1.0,...,4.0,3.0,4.0,2.0,1.0,4.0,2.0,1.0,4.0,4.0

In [7]:
data_prep.x_test

,C1e,C4d,A2h,B2d,C1c,B4b,B4c,A3b,A3j,C4a,...,B9,A3d,B2b,A2e,c4m,B4d,D8,C4i,C1f,B4a
1973,1.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,3.0,1.0,...,3.0,3.0,3.0,2.0,1.0,3.0,4.0,1.0,1.0,1.0
179,2.0,1.0,1.0,6.0,2.0,4.0,4.0,3.0,3.0,2.0,...,3.0,3.0,5.0,3.0,2.0,7.0,2.0,1.0,1.0,5.0
2309,1.0,1.0,7.0,7.0,1.0,7.0,4.0,6.0,7.0,2.0,...,6.0,4.0,7.0,4.0,1.0,7.0,2.0,1.0,1.0,7.0
1218,2.0,2.0,2.0,4.0,2.0,2.0,3.0,6.0,4.0,2.0,...,1.0,3.0,2.0,2.0,1.0,3.0,3.0,1.0,4.0,3.0
591,1.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0,3.0,...,2.0,5.0,1.0,1.0,2.0,1.0,4.0,1.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
712,2.0,2.0,4.0,1.0,3.0,4.0,2.0,5.0,6.0,2.0,...,3.0,4.0,1.0,7.0,2.0,7.0,1.0,1.0,2.0,7.0
1532,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,1.0,2.0,...,1.0,1.0,1.0,1.0,2.0,1.0,4.0,1.0,1.0,1.0
2615,2.0,1.0,1.0,2.0,1.0,2.0,2.0,2.0,1.0,2.0,...,1.0,2.0,1.0,1.0,1.0,2.0,1.0,1.0,1.0,2.0
1024,1.0,1.0,1.0,1.0,2.0,2.0,2.0,2.0,2.0,2.0,...,3.0,2.0,1.0,1.0,1.0,3.0,3.0,1.0,1.0,2.0
1720,2.0,1.0,2.0,4.0,2.0,1.0,1.0,2.0,3.0,2.0,...,3.0,2.0,2.0,3.0,2.0,3.0,2.0,1.0,1.0,3.0

In [8]:
data_prep.y_train

1422    2
2202    3
2249    3
738     3
2629    2
       ..
1598    2
75      3
925     3
87      3
2457    2
Name: AgencySize, Length: 1421, dtype: int64

In [9]:
data_prep.y_test

1973    3
179     3
2309    3
1218    3
591     3
       ..
712     3
1532    2
2615    2
1024    3
1720    2
Name: AgencySize, Length: 871, dtype: int64

# Exploratory Factor Analysis

The efa is automatically performed on the training dataset. If you set n_factors to estimate, then the process will estimate a number of factors equal to the number of items and provide Eigenvalues.

In [10]:
sa = ScaleAnalyzer(data_preparator=data_prep)
efa_factor_loadings = sa.efa(rotation='oblimin', estimation='ml', n_factors='estimate')
efa_factor_loadings

array([22.99672096,  4.48378134,  3.42187001,  2.4944326 ,  2.08832157,
        1.90837882,  1.68759135,  1.4222784 ,  1.40202798,  1.34968674,
        1.26814922,  1.20957741,  1.10804609,  1.02610582,  0.98826576,
        0.94685702,  0.92386562,  0.89724608,  0.84929106,  0.83312517,
        0.79580192,  0.77492917,  0.76513262,  0.73130439,  0.70502681,
        0.69444574,  0.6740148 ,  0.65223305,  0.63102516,  0.60975828,
        0.57865778,  0.55917524,  0.55414351,  0.53854878,  0.5200498 ,
        0.51231506,  0.49508844,  0.48325153,  0.46486319,  0.46172752,
        0.44813209,  0.43422225,  0.42782786,  0.41237472,  0.40405219,
        0.40066601,  0.38368541,  0.37470819,  0.36734001,  0.36021531,
        0.35113819,  0.33227995,  0.32442684,  0.32373555,  0.30252876,
        0.27444178,  0.27178322,  0.2683454 ,  0.25653354,  0.24824433,
        0.23598002,  0.22903379,  0.21781735,  0.21561457,  0.19514438,
        0.19160273,  0.18154254,  0.16951237,  0.16360004,  0.15683477,
        0.14451397,  0.13007253,  0.11550628,  0.09873304,  0.08069822])

Based on these results, I have decided to keep 5 factors (eigenvalues over 2). This is fairly trivial in the grand-scheme...there are statistical methods to help determine the number of factors and also you can use the 'old reliable' scree plot. That isn't important for this tutorial, so we will be moving on, but maybe you want to add that in for yourself later!

Running the EFA again, but this time n_factors is set to 5.

In [11]:
sa = ScaleAnalyzer(data_preparator=data_prep)
efa_factor_loadings = sa.efa(rotation='oblimin', estimation='ml', n_factors=5)
efa_factor_loadings

     factor_1  factor_2  factor_3  factor_4  factor_5  max_load
C1e -0.050212  0.174682  0.060540  0.514327  0.231857  factor_4
C4d  0.098881  0.533627  0.009345 -0.061396  0.130439  factor_2
A2h  0.677056  0.003623 -0.073291  0.090305  0.008690  factor_1
B2d  0.035739 -0.063175  0.536766  0.169716  0.036690  factor_3
C1c  0.282338  0.054403  0.066816  0.081120  0.367560  factor_5
..        ...       ...       ...       ...       ...       ...
B4d  0.502260 -0.045516  0.130655  0.076859  0.207297  factor_1
D8   0.136201  0.049939  0.000742 -0.044106 -0.265711  factor_1
C4i -0.050369  0.579765  0.062090  0.014137 -0.011149  factor_2
C1f  0.089557  0.102697  0.160898  0.205742  0.284404  factor_5
B4a  0.422686  0.026626  0.136822  0.079800  0.154193  factor_1

[75 rows x 6 columns]

At first glance, we can already see some items that have poor loadings across factors (e.g. D8). Again, not important for the tutorial so we will move on, but maybe its possible to add a process that would automatically remove any items that have eigenvalues all below a set threshold. If you decide to do this, don't forget that you will need to update the scale_dict to reflect the dropped items for downstream procedures!

# Confirmatory Factor Analysis (but not my favorite package)

We can use the scale_dict that was created by our EFA.

In [12]:
cfa_output = sa.cfa(scale_dict=sa.scale_dict)
cfa_output

C:\Users\Joshua\anaconda3\envs\test_env\lib\site-packages\factor_analyzer\confirmatory_factor_analyzer.py:753: UserWarning: The optimization routine failed to converge: ABNORMAL_TERMINATION_IN_LNSRCH
  warnings.warn(

,factor_1,factor_2,factor_3,factor_4,factor_5,factor_error_1,factor_error_2,factor_error_3,factor_error_4,factor_error_5
A2h,0.892981,0.0,0.0,0.0,0.000000,0.036571,0.0,0.0,0.0,0.000000
B4b,0.921070,0.0,0.0,0.0,0.000000,0.038671,0.0,0.0,0.0,0.000000
A3b,1.126802,0.0,0.0,0.0,0.000000,0.039916,0.0,0.0,0.0,0.000000
A3j,1.141705,0.0,0.0,0.0,0.000000,0.037980,0.0,0.0,0.0,0.000000
A3c,1.150487,0.0,0.0,0.0,0.000000,0.040208,0.0,0.0,0.0,0.000000
...,...,...,...,...,...,...,...,...,...,...
C1g,0.000000,0.0,0.0,0.0,1.071498,0.000000,0.0,0.0,0.0,0.044088
B5b,0.000000,0.0,0.0,0.0,1.093106,0.000000,0.0,0.0,0.0,0.040076
C8,0.000000,0.0,0.0,0.0,0.924700,0.000000,0.0,0.0,0.0,0.034045
B5a,0.000000,0.0,0.0,0.0,1.097847,0.000000,0.0,0.0,0.0,0.041325
C1f,0.000000,0.0,0.0,0.0,1.083918,0.000000,0.0,0.0,0.0,0.041530

Yikes, a warning that we didn't converge! OK, I admit that we should probably parse down the items based on EFA results, but I'm still going to ignore it and leave the audiance with something to think about. Don't worry though, you can create you own scale dictionary based on your observations and pass that to the methods instead, so its still flexible!

# Polytomous IRT using the Graded Unfolding Model (GUM)

The warning that appears is caused because the items have different scale ranges (e.g., 1-7), so some items have a shorter range and will cause this warning to appear. Wherever you see a nan values to difficulty or tau, its because the range for them items did not extend to those values.

In [13]:
irt_stats_res, abilities = sa.irt_gum(scale_dict=sa.scale_dict)
irt_stats_res

C:\Users\Joshua\anaconda3\envs\pragmatic_programming\lib\site-packages\scipy\optimize\_optimize.py:284: RuntimeWarning: Values in x were outside bounds during a minimize step, clipping to bounds
  warnings.warn("Values in x were outside bounds during a "

              discrimination  difficulty_1  difficulty_2  difficulty_3  \
factor_1 D3         0.277097     -0.606992           NaN           NaN
         A2b        1.623495     -0.974138     -0.083830      0.163393
         A3k        4.000000     -1.525241     -0.893998     -0.599165
         B4b        0.877290     -1.337922     -0.477479      0.155858
         A2h        1.523576     -0.816549     -0.247100     -0.564002
...                      ...           ...           ...           ...
factor_5 B5b        4.000000     -0.511450      0.002111      0.076798
         D14        1.213522     -3.503928           NaN           NaN
         B5d        1.758469     -0.236407      0.411423      0.285929
         C2         2.634951      0.234306           NaN           NaN
         B8         0.304323      3.648002      1.647798           NaN

              difficulty_4  difficulty_5  difficulty_6  difficulty_7  \
factor_1 D3            NaN           NaN           NaN           NaN
         A2b     -0.601003     -0.131532      0.063021           NaN
         A3k     -0.354329     -0.247600     -0.203717      0.978090
         B4b     -0.013984      0.073124     -0.678386      1.503359
         A2h      0.618456     -0.114243     -0.148629      2.444632
...                    ...           ...           ...           ...
factor_5 B5b      0.443668      0.357285      0.239509      0.507539
         D14           NaN           NaN           NaN           NaN
         B5d      0.603355      0.632415      0.025260      0.786389
         C2            NaN           NaN           NaN           NaN
         B8            NaN           NaN           NaN           NaN

              difficulty_8  difficulty_9  ...  difficulty_13  difficulty_14  \
factor_1 D3       2.000000           NaN  ...            NaN            NaN
         A2b     -0.054621           NaN  ...      -0.272635      -0.025413
         A3k      0.113270     -0.751550  ...       0.825705       1.120537
         B4b     -0.005449     -1.514257  ...      -0.166756       0.466581
         A2h      0.083082     -2.278468  ...       0.730166       0.413264
...                    ...           ...  ...            ...            ...
factor_5 B5b      0.376188      0.244836  ...       0.675577       0.750265
         D14     -0.387837           NaN  ...            NaN            NaN
         B5d      0.369971     -0.046447  ...       0.454013       0.328519
         C2      -0.247447           NaN  ...            NaN            NaN
         B8      -0.720706           NaN  ...            NaN      -3.089210

              difficulty_15      tau1      tau2      tau3      tau4      tau5  \
factor_1 D3        4.606992 -2.606992       NaN       NaN       NaN       NaN
         A2b       0.864896 -0.919517 -0.029208  0.218014 -0.546382 -0.076911
         A3k       1.751780 -1.638510 -1.007268 -0.712435 -0.467598 -0.360870
         B4b       1.327025 -1.332473 -0.472030  0.161307 -0.008535  0.078573
         A2h       0.982713 -0.899631 -0.330182 -0.647084  0.535375 -0.197325
...                     ...       ...       ...       ...       ...       ...
factor_5 B5b       1.263825 -0.887638 -0.374077 -0.299390  0.067481 -0.018903
         D14       2.728255 -3.116091       NaN       NaN       NaN       NaN
         B5d       0.976349 -0.606378  0.041452 -0.084042  0.233384  0.262444
         C2       -0.729201  0.481753       NaN       NaN       NaN       NaN
         B8       -5.089414  4.368708  2.368504       NaN       NaN       NaN

                  tau6      tau7
factor_1 D3        NaN       NaN
         A2b  0.117642       NaN
         A3k -0.316987  0.864820
         B4b -0.672937  1.508808
         A2h -0.231711  2.361550
...                ...       ...
factor_5 B5b -0.136679  0.131352
         D14       NaN       NaN
         B5d -0.344712  0.416418
         C2        NaN       NaN
         B8        NaN       NaN

[75 rows x 23 columns]

Notice that this is a multi-index DF, where the factor is the first index, and the second indicies are the items in that factor. We can access Factor 1 as such...

In [14]:
irt_stats_res.loc['factor_1', :, :]

,discrimination,difficulty_1,difficulty_2,difficulty_3,difficulty_4,difficulty_5,difficulty_6,difficulty_7,difficulty_8,difficulty_9,...,difficulty_13,difficulty_14,difficulty_15,tau1,tau2,tau3,tau4,tau5,tau6,tau7
D3,0.277097,-0.606992,NaN,NaN,NaN,NaN,NaN,NaN,2.000000,NaN,...,NaN,NaN,4.606992,-2.606992,NaN,NaN,NaN,NaN,NaN,NaN
A2b,1.623495,-0.974138,-0.083830,0.163393,-0.601003,-0.131532,0.063021,NaN,-0.054621,NaN,...,-0.272635,-0.025413,0.864896,-0.919517,-0.029208,0.218014,-0.546382,-0.076911,0.117642,NaN
A3k,4.000000,-1.525241,-0.893998,-0.599165,-0.354329,-0.247600,-0.203717,0.978090,0.113270,-0.751550,...,0.825705,1.120537,1.751780,-1.638510,-1.007268,-0.712435,-0.467598,-0.360870,-0.316987,0.864820
B4b,0.877290,-1.337922,-0.477479,0.155858,-0.013984,0.073124,-0.678386,1.503359,-0.005449,-1.514257,...,-0.166756,0.466581,1.327025,-1.332473,-0.472030,0.161307,-0.008535,0.078573,-0.672937,1.508808
A2h,1.523576,-0.816549,-0.247100,-0.564002,0.618456,-0.114243,-0.148629,2.444632,0.083082,-2.278468,...,0.730166,0.413264,0.982713,-0.899631,-0.330182,-0.647084,0.535375,-0.197325,-0.231711,2.361550
C1b,1.323601,-0.952595,-0.177479,-0.417558,-0.032477,-0.048171,-0.504950,0.936153,0.145504,-0.645144,...,0.708567,0.468488,1.243604,-1.098100,-0.322984,-0.563062,-0.177981,-0.193676,-0.650455,0.790649
A3j,4.000000,-1.607917,-0.961255,-0.575587,-0.396051,-0.194857,-0.237419,0.941602,0.115600,-0.710403,...,0.806787,1.192455,1.839117,-1.723517,-1.076855,-0.691187,-0.511651,-0.310457,-0.353019,0.826002
A2d,1.378210,-1.234549,-0.320042,0.261654,-0.774905,-0.138656,-0.360665,1.950546,-0.005227,-1.961000,...,-0.272109,0.309587,1.224095,-1.229322,-0.314815,0.266881,-0.769678,-0.133429,-0.355438,1.955773
A2a,2.179436,-1.287141,-0.542136,0.109416,-0.585928,-0.413006,-0.127021,NaN,-0.128648,NaN,...,-0.366712,0.284841,1.029845,-1.158493,-0.413489,0.238064,-0.457280,-0.284358,0.001627,NaN
A3m,3.805644,-1.303260,-0.775616,-0.582583,-0.243584,-0.275853,-0.226737,1.036459,0.151580,-0.733298,...,0.885744,1.078777,1.606421,-1.454840,-0.927197,-0.734163,-0.395165,-0.427434,-0.378317,0.884878
A1a,2.059074,-1.453987,-0.396953,-0.001342,-0.509769,-0.198441,-0.038370,NaN,-0.057210,NaN,...,-0.113078,0.282533,1.339567,-1.396777,-0.339743,0.055868,-0.452559,-0.141231,0.018840,NaN
D8,0.325002,-3.217147,-0.330561,2.233404,6.719223,NaN,NaN,NaN,2.000000,NaN,...,1.766596,4.330561,7.217147,-5.217147,-2.330561,0.233404,4.719223,NaN,NaN,NaN
A3b,2.695966,-1.871206,-0.971549,-0.389987,-0.659140,-0.287968,-0.282566,1.324125,0.214811,-0.894503,...,0.819609,1.401170,2.300828,-2.086017,-1.186360,-0.604798,-0.873951,-0.502778,-0.497377,1.109314
A3h,1.979246,-1.171419,-0.571807,-0.369487,-0.097665,-0.080672,-0.226152,1.501050,0.164329,-1.172391,...,0.698146,0.900465,1.500078,-1.335749,-0.736136,-0.533817,-0.261995,-0.245002,-0.390481,1.336720
A3i,1.776119,-1.393540,-0.752857,-0.573482,0.054091,-0.259123,-0.306736,2.099089,0.101189,-1.896712,...,0.775859,0.955234,1.595917,-1.494729,-0.854046,-0.674671,-0.047097,-0.360312,-0.407925,1.997901
A3f,1.417836,-1.265146,-0.495182,-0.066351,-0.389326,-0.039704,-0.306282,2.395286,0.133884,-2.127519,...,0.334118,0.762949,1.532913,-1.399030,-0.629065,-0.200235,-0.523209,-0.173587,-0.440165,2.261402
B1a,1.499205,-1.609924,-0.676946,-0.014157,-0.874186,-0.346534,-0.430159,2.051991,0.059916,-1.932159,...,0.133989,0.796779,1.729757,-1.669841,-0.736862,-0.074073,-0.934102,-0.406450,-0.490075,1.992075
A3c,3.129279,-1.548999,-0.812814,-0.483962,-0.433378,-0.335011,-0.201771,1.168506,0.194813,-0.778880,...,0.873588,1.202440,1.938625,-1.743812,-1.007627,-0.678775,-0.628191,-0.529824,-0.396584,0.973693
C1a,1.479466,-0.634360,-0.073360,0.027658,0.395621,-0.094513,-0.269976,1.079988,0.110446,-0.859096,...,0.193234,0.294251,0.855252,-0.744806,-0.183805,-0.082788,0.285175,-0.204958,-0.380422,0.969542
B4d,1.179393,-1.728536,-0.902981,-0.601359,-0.408763,-0.381414,-0.891840,1.181780,-0.002737,-1.187254,...,0.595884,0.897507,1.723062,-1.725799,-0.900244,-0.598621,-0.406026,-0.378676,-0.889102,1.184517
A3e,1.203947,-1.937640,-0.785397,-0.840950,-0.377248,-0.300735,-0.602139,1.065979,0.098181,-0.869617,...,1.037311,0.981758,2.134001,-2.035820,-0.883577,-0.939130,-0.475429,-0.398916,-0.700320,0.967798
A3d,1.184479,-1.746994,-0.781884,-0.175411,-0.172236,-0.138322,-0.163866,1.492260,0.200709,-1.090843,...,0.576829,1.183301,2.148411,-1.947703,-0.982593,-0.376120,-0.372945,-0.339031,-0.364575,1.291552
B1b,1.552056,-1.554183,-0.695352,-0.293335,-0.689488,-0.335158,-0.567971,1.970219,0.014301,-1.941617,...,0.321937,0.723955,1.582785,-1.568484,-0.709653,-0.307636,-0.703789,-0.349459,-0.582272,1.955918
A1b,3.020475,-1.369639,-0.566657,-0.262398,-0.546588,-0.199551,-0.053785,NaN,0.138359,NaN,...,0.539116,0.843375,1.646357,-1.507998,-0.705016,-0.400757,-0.684947,-0.337910,-0.192144,NaN
B4a,0.849411,-1.410973,-0.571380,0.056880,-0.652991,-0.357039,-1.040412,2.427059,-0.003798,-2.434655,...,-0.064476,0.563784,1.403377,-1.407175,-0.567582,0.060678,-0.649192,-0.353241,-1.036614,2.430857
A2f,1.929301,-1.519174,-0.921081,-0.325166,-0.547867,-0.389663,-0.442844,1.983747,-0.006605,-1.996957,...,0.311955,0.907871,1.505963,-1.512568,-0.914476,-0.318560,-0.541262,-0.383058,-0.436239,1.990352
A2c,2.065406,-0.898660,-0.160241,-0.003040,-0.154966,-0.045679,-0.063039,1.354855,-0.068367,-1.491588,...,-0.133694,0.023507,0.761927,-0.830293,-0.091874,0.065327,-0.086600,0.022688,0.005327,1.423222
A3a,3.375220,-1.550233,-0.764469,-0.369282,-0.436631,-0.298965,-0.177991,1.087208,0.205063,-0.677081,...,0.779409,1.174595,1.960360,-1.755297,-0.969532,-0.574346,-0.641694,-0.504028,-0.383054,0.882145
A2g,1.410366,-1.807287,-1.094811,-0.729809,-0.676267,-0.587242,-0.826559,1.622569,-0.016563,-1.655695,...,0.696683,1.061685,1.774161,-1.790724,-1.078248,-0.713246,-0.659704,-0.570679,-0.809997,1.639132
A2e,1.568177,-1.355405,-0.572509,-0.189625,-0.507365,-0.429915,-0.330482,3.015132,-0.153189,-3.321510,...,-0.116754,0.266130,1.049026,-1.202216,-0.419320,-0.036436,-0.354176,-0.276725,-0.177292,3.168321
A3g,0.917945,-0.993914,-0.234472,0.558520,-0.418456,0.012686,-0.455570,2.160066,0.102000,-1.956066,...,-0.354520,0.438471,1.197913,-1.095914,-0.336472,0.456520,-0.520455,-0.089313,-0.557570,2.058066
A3l,2.534193,-1.145228,-0.637139,-0.577773,0.122766,-0.194918,-0.204119,1.266943,0.116840,-1.033264,...,0.811452,0.870819,1.378907,-1.262067,-0.753979,-0.694612,0.005926,-0.311758,-0.320959,1.150103

### Ability Scores

In [16]:
abilities

,factor_1_ability,factor_2_ability,factor_3_ability,factor_4_ability,factor_5_ability
0,0.821214,0.309816,-0.011158,-0.188928,-0.748167
1,1.416926,-0.339159,-0.166827,-0.188928,-1.054363
2,0.330421,-0.008743,-0.371494,0.241302,0.406315
3,0.000884,-0.022510,-0.450657,-0.111638,0.131712
4,-0.808031,0.102103,0.521153,-0.090859,-0.465613
...,...,...,...,...,...
2896,-0.950486,0.102103,-0.166827,-0.188928,-0.654103
2897,1.828037,0.102103,0.220567,0.038096,1.509371
2898,1.009724,-0.162208,0.658985,0.678350,0.897157
2899,0.996696,-0.307168,-0.055297,-0.188928,0.201886
2900,0.339314,0.000190,-0.203482,0.002230,0.349496

# Create Scale Means from EFA output

In [17]:
scales_data = sa.create_scales(scale_dict=sa.scale_dict, dataset=data_prep.data.drop(labels=[dep_var], axis=1))
# merge in the independent variable
scales_data = scales_data.merge(data_prep.data[dep_var].to_frame(), left_index=True, right_index=True)
scales_data

      factor_1  factor_2  factor_3  factor_4  factor_5  AgencySize
0      3.00000  1.066667     1.500  1.166667  1.642857           3
1      1.09375  1.266667     1.000  1.166667  1.214286           3
2      4.75000  1.866667     1.375  2.500000  2.642857           3
3      5.25000  1.800000     1.750  2.833333  2.714286           3
4      2.25000  1.000000     2.750  1.833333  1.428571           3
...        ...       ...       ...       ...       ...         ...
2896   2.18750  1.000000     1.000  1.166667  1.357143           2
2897   1.43750  1.000000     1.125  1.833333  1.142857           2
2898   2.59375  1.266667     1.875  1.166667  1.571429           2
2899   2.59375  1.133333     1.125  1.166667  2.071429           2
2900   4.78125  1.866667     4.875  4.500000  2.857143           2

[2901 rows x 6 columns]

Create a new DataPreparator using the scales_data

In [18]:
scales_data_prep = DataPreparator(data=scales_data, features=list(scales_data.columns[0:-1].values), dep_var=dep_var)
scales_data_prep.split_data(val_set=False, test_size=.30, random_state=456)

# Create a Machine Learning Ensemble to predict agency size based on satisfaction survey results

We need to create a dictionary with the models we want and the keyword arguments we want to pass. The only model available right now are: linear regression, support vector regressor, random forest regressor, and k-nearest neighbor.

In [19]:
 model_specs = {
        'lr': {},
        'knn': {
           'n_neighbors': 5,
            'leaf_size': 20
        },
        'svr': {
            'kernel': 'rbf'
        },
        'rf': {
            'n_estimators': 50,
            'max_depth': 10
        }
    }

In [20]:
ensemble = EnsembleModeler(model_specs=model_specs, data_preparator=scales_data_prep)
ens_train_res, ens_test_res = ensemble.test_ensemble()
ens_train_res

          MAE       MSE        r2
lr   0.541587  0.380199  0.017457
knn  0.449683  0.310401  0.197835
svr  0.442636  0.421691 -0.089771
rf   0.531401  0.368242 -0.022388

In [21]:
ens_test_res

               MAE       MSE        r2
lr        0.536214  0.361172 -0.002759
knn       0.540987  0.430769 -0.195989
svr       0.456709  0.414305 -0.150277
rf        0.531401  0.368242 -0.022388
ensemble  0.515416  0.362678 -0.006941

So, the models are not good. Probably because I didn't remove some poor performing items ealier...ooops. Maybe you can do a better job than me by making some improvements?